[package]
name = "mcpatcher"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
getch-rs = { version = "0.2.0" }
sha2 = "0.10"
hex = "0.4"
winapi = "0.2.8"
kernel32-sys = "0.2.1"