name: Build for Windows and Upload Debug Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    name: Build Windows x86_64 Debug Binary
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add Windows target
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build in Debug mode
        run: cargo build --target x86_64-pc-windows-msvc

      - name: Zip Debug Binary
        if: startsWith(github.event.release.tag_name, 'nightly')
        shell: pwsh
        run: |
          # Adjust the path to where your debug binary is located.
          # For a binary crate, the debug binary is usually in:
          # target\x86_64-pc-windows-msvc\debug\your_binary.exe
          # Replace 'your_binary.exe' with the actual name of your binary.
          $ErrorActionPreference = 'Stop'
          $binaryPath = "target\x86_64-pc-windows-msvc\debug\your_binary.exe"
          $zipPath = "x64_debug_binary.zip"
          if (-Not (Test-Path $binaryPath)) {
              Write-Error "Binary not found at $binaryPath"
              exit 1
          }
          Compress-Archive -Path $binaryPath -DestinationPath $zipPath
          Write-Host "Artifact $zipPath created."
      
      - name: Upload Debug Artifact
        if: startsWith(github.event.release.tag_name, 'nightly')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: x64_debug_binary.zip
          artifacts: x64_debug_binary.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
